package com.andjava.ide.project;

import com.andjava.ide.build.BuildPaths;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * 生成 BuildConfig.java，包含构建时常量
 */
public class BuildConfigGenerator {

    /**
     * @return 写入的 BuildConfig.java 文件，失败返回 null
     */
    public File generate(ProjectConfig cfg, boolean debug) {
        File genPkg = BuildPaths.genPackageDir(cfg);
        if (!genPkg.exists() && !genPkg.mkdirs()) {
            cfg.addError("无法创建 gen 目录: " + genPkg);
            return null;
        }
        File out = BuildPaths.generatedBuildConfig(cfg);
        try {
            PrintWriter pw = new PrintWriter(out, "UTF-8");
            try {
                pw.println("// Auto-generated by AndJava BuildConfigGenerator. Do not edit.");
                pw.println("package " + cfg.getJavaPackage() + ";");
                pw.println();
                pw.println("public final class BuildConfig {");
                pw.println("    private BuildConfig() {}");
                pw.println();
                pw.println("    public static final boolean DEBUG = " + (debug ? "true" : "false") + ";");
                pw.println("    public static final String APPLICATION_ID = \"" + escape(cfg.getApplicationId()) + "\";");
                pw.println("    public static final String BUILD_TYPE = \"" + (debug ? "debug" : "release") + "\";");
                pw.println("    public static final int VERSION_CODE = " + cfg.getVersionCode() + ";");
                pw.println("    public static final String VERSION_NAME = \"" + escape(cfg.getVersionName()) + "\";");
                pw.println("    public static final int COMPILE_SDK = " + cfg.getCompileSdk() + ";");
                pw.println("    public static final int MIN_SDK = " + cfg.getMinSdk() + ";");
                pw.println("    public static final int TARGET_SDK = " + cfg.getTargetSdk() + ";");
                pw.println("}");
                pw.flush();
            } finally {
                try { pw.close(); } catch (Exception ignored) {}
            }
            return out;
        } catch (IOException e) {
            cfg.addError("写入 BuildConfig.java 失败: " + e.getMessage());
            return null;
        }
    }

    private String escape(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
